version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy
hooks:
  BeforeInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user