server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    # Eureka 서버로부터 서비스 목록을 가져오는 간격
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes: # 라우팅 설정


        # Member Service

        - id: auth-service # AuthService 는 MemberService 모듈 안에서 관리
          predicates:
            - Path=/member-service/v*/oauth/**
          uri: lb://MEMBER-SERVICE
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        - id: member-service-swagger-ui
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/v3/api-docs
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        
        - id: member-service-sample
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/sample/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}

        - id: member-service-auth
          predicates:
            - Path=/member-service/**
          uri: lb://MEMBER-SERVICE
          filters:
            - AuthorizationFilter
            - RewritePath=/member-service/(?<segment>.*), /$\{segment} # /member-service/xxx 로 요청이 오면 /xxx 로 변경하여 요청한다.

        # Buddy Service Route Set
        - id: buddy-service-swagger-ui # Swagger UI 라우팅 우선순위로 설정되어야 하므로 buddy-service-with-auth 보다 위에 위치함.
          uri: lb://BUDDY-SERVICE
          predicates:
            - Path=/buddy-service/v3/api-docs
          filters:
            - RewritePath=/buddy-service/(?<segment>.*), /$\{segment}
        - id: buddy-service-with-auth  # API 설정
          predicates:
            - Path=/buddy-service/**
          uri: lb://BUDDY-SERVICE
          filters:
            - AuthorizationFilter
            - RewritePath=/buddy-service/(?<segment>.*), /$\{segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service # 추후 API GateWay Swagger는 제거.
        url: /v3/api-docs
      - name: member-service
        url: http://localhost:${server.port}/member-service/v3/api-docs
      - name: buddy-service
        url: /v3/api-docs/buddy-service
      - name: community-service
        url: http://localhost:${server.port}/v3/api-docs/community-service

swagger:
  servers:
    title: "BuddyMe Service Swagger"
    version: "V1"
    url: http://localhost:8000
    description: Local Gateway Server

jwt:
  key: ${JWT_KEY}