server:
  port: 8080 # random port

debug: false

management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.freediving.communityservice: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: community-service
  data:
    mongodb:
      uri: ${MONGODB_ATLAS_URI}
      database: sample_mflix

  datasource:
    # PostgreSQL 설정
    url: jdbc:postgresql://localhost:5432/commdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

    # H2 설정
    # url: jdbc:h2:mem:community;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # username: sa
    # password:
    # driver-class-name: org.h2.Driver

  jpa:
    hibernate.ddl-auto: none
    # H2 설정
    # database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      encoding: utf-8
      mode: always

  h2:
    console:
      enabled: false # H2 콘솔 사용시 true로 변경
      path: /h2-console

  output:
    ansi:
      enabled: always # IntelliJ CE Console Color

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

swagger:
  servers:
    title: "Community Service Swagger"
    version: "v1"
    url: http://localhost:8080
    description: Local Community

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

community:
  gateway:
    fqdn: http://localhost:8080
