server:
  port: 40000 # 랜덤 포트 할당

spring:
  application:
    name: buddy-service
  # Only for Local Test
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
    # Datasource
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:~/buddy;Mode=Oracle
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: create-drop
eureka:
  instance:
    hostname: localhost
    #    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    # Eureka 서버 등록
    register-with-eureka: true
    # Eureka 서버로부터 인스턴스 정보를 주기적으로 가져오는 기능
    fetch-registry: true
    # Eureka 서버 위치 등록
    service-url:
      # endpoint 지정
      defaultZone: http://localhost:8761/eureka

swagger:
  servers:
    title: "Buddy Service Swagger"
    version: "V1"
    url: http://localhost:8000/${spring.application.name}
    description: Local Gateway Server
