server:
  port: 40000 # 랜덤 포트 할당

spring:
  application:
    name: buddy-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:buddy;Mode=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
eureka:
  instance:
    hostname: localhost
    #    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    # Eureka 서버 등록
    register-with-eureka: true
    # Eureka 서버로부터 인스턴스 정보를 주기적으로 가져오는 기능
    fetch-registry: true
    # Eureka 서버 위치 등록
    service-url:
      # endpoint 지정
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

swagger:
  servers:
    title: "Buddy Service Swagger"
    version: "V1"
    #url: http://localhost:8000/${spring.application.name}
    url: http://localhost:40000
    description: Local Gateway Server
