name: CI & CD for buddy-service

on:
  push:
    paths:
      - 'buddy-service/**'
    branches: [ "feat/#50" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-dev.yml
        run: |
          echo "$BUDDY_APPLICATION_DEV_YML" > ./buddy-service/src/main/resources/application-dev.yml
        env:
          BUDDY_APPLICATION_DEV_YML: ${{ secrets.BUDDY_APPLICATION_DEV_YML }}

      - name: Build with Gradle
        run: |
          ./gradlew buddy-service:build

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      # Jar 파일 Copy
      - name: Copy Jar
        run: |
          cp ./buddy-service/build/libs/*.jar ./deploy/
          cp ./buddy-service/appspec.yml ./deploy/
          cp -r ./buddy-service/scripts ./deploy/

      # 압축파일 형태로 전달
      - name: Make zip file
        run: |
          cd deploy
          zip -r ../buddy-service.zip .

      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private ./buddy-service.zip s3://buddyme-bucket/deploy/buddy-service.zip
                # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name service-codedeploy \
          --deployment-group-name buddy-service-codedeploy \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=buddyme-bucket,bundleType=zip,key=deploy/buddy-service.zip \
          --region ap-northeast-2
