name: CI & CD for discovery-service-mac

on:
  push:
    #    paths:
    #      - 'discovery-service/**'
    branches: [ "deploy/**" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-prd.yml
        run: |
          echo "${{ secrets.DISCOVERY_APPLICATION_PRD_YML }}" > ./discovery-service/src/main/resources/application-prd.yml
      - name: Build with Gradle
        run: ./gradlew discovery-service:build
      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg PROFILE=prd -t ${{ secrets.DOCKER_REPO }}/discovery-service-prd ./discovery-service
          docker push ${{ secrets.DOCKER_REPO }}/discovery-service-prd
      - name: Docker pull and Docker-compose up
        run: |
          docker pull ${{ secrets.DOCKER_REPO }}/discovery-service-prd
          docker image prune -a -f
          docker-compose -f $HOME/buddyme/docker-compose.yml up -d




