name: CI & CD for discovery-service-gcp

on:
  push:
    paths:
      - 'discovery-service/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-gcp.yml
        run: |
          touch ./discovery-service/src/main/resources/application-gcp.yml
          echo "${{ secrets.DISCOVERY_APPLICATION_GCP_YML }}" > ./discovery-service/src/main/resources/application-gcp.yml
      - name: Build with Gradle
        run: ./gradlew discovery-service:build
      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/discovery-service ./discovery-service
          docker push ${{ secrets.DOCKER_REPO }}/discovery-service
# Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "34.125.28.33"
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.GCP_SSH_PASSPHRASE }}
          script: | 
            sudo docker pull ${{ secrets.DOCKER_REPO }}/discovery-service
            sudo docker image prune -a -f
            docker-compose -p discovery -f /docker/docker-compose-discovery.yml up -d
