name: CI & CD for discovery-service

on:
  push:
    paths:
      - 'discovery-service/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-dev.yml
        run: |
          touch ./discovery-service/src/main/resources/application-dev.yml
          echo "${{ secrets.DISCOVERY_APPLICATION_DEV_YML }}" > ./discovery-service/src/main/resources/application-dev.yml

      - name: Build with Gradle
        run: |
          ./gradlew discovery-service:build

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/discovery-service ./discovery-service
          docker push ${{ secrets.DOCKER_REPO }}/discovery-service

      - name: AWS EC2 remote ssh and command by appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DISCOVERY_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DISCOVERY_EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/discovery-service
            sudo docker stop $(sudo docker ps -a | grep discovery-service | awk '{print $1}')
            sudo docker rm $(sudo docker ps -a | grep discovery-service | awk '{print $1}')
            sudo docker image prune -a -f
            sudo docker-compose -p discovery -f /docker/docker-compose-discovery-${{ secrets.SERVER_PROFILE }}.yml down --rmi all
            sudo docker-compose -p discovery -f /docker/docker-compose-discovery-${{ secrets.SERVER_PROFILE }}.yml up -d