name: CI & CD for gateway-service

on:
  push:
    paths:
      - 'gateway-service/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-dev.yml
        run: |
          echo "$GATEWAY_APPLICATION_DEV_YML" > ./gateway-service/src/main/resources/application-dev.yml
        env:
          BUDDY_APPLICATION_DEV_YML: ${{ secrets.GATEWAY_APPLICATION_DEV_YML }}
      - name: Build with Gradle
        run: |
          ./gradlew gateway-service:build

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/gateway-service ./gateway-service
          docker push ${{ secrets.DOCKER_REPO }}/gateway-service

      - name: AWS EC2 remote ssh and command by appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GATEWAY_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.GATEWAY_EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/gateway-service
            sudo docker stop $(sudo docker ps -a | grep gateway-service | awk '{print $1}')
            sudo docker rm $(sudo docker ps -a | grep gateway-service | awk '{print $1}')
            sudo docker image prune -a -f 
            sudo docker-compose -p gateway -f /docker/docker-compose-gateway-${{ secrets.SERVER_PROFILE }}.yml down --rmi all
            sudo docker-compose -p gateway -f /docker/docker-compose-gateway-${{ secrets.SERVER_PROFILE }}.yml up -d
