name: CI & CD for member-service-gcp

on:
  push:
    paths:
      - 'member-service/**'
    branches: [ "main" ]

env:
  MEMBER_APPLICATION_DEV_GCP_YML: ${{ secrets.MEMBER_APPLICATION_DEV_GCP_YML }}

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Create application-dev.yml
        run: |
          touch ./member-service/src/main/resources/application-dev.yml
          echo "$MEMBER_APPLICATION_DEV_GCP_YML" > ./member-service/src/main/resources/application-dev.yml
      - name: Build with Gradle
        run: ./gradlew member-service:build
      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg PROFILE=dev -t ${{ secrets.DOCKER_REPO }}/member-service ./member-service
          docker push ${{ secrets.DOCKER_REPO }}/member-service
      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "34.64.196.150"
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          #passphrase: ${{ secrets.GCP_SSH_PASSPHRASE }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/member-service
            sudo docker image prune -a -f
            docker-compose -f /docker/docker-compose.yml up -d
